name: AWS Build n Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v2
        #id: yarn-cache
        with:
          path: '**/node_modules'
          #key:${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          key:${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          #restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn  install
      - name: Build
        run: yarn build
      - name: Deploy
        run: aws s3 sync ./dist s3://aws-codedeploy-nodejs-eu-west-2.s3.eu-west-2.amazonaws.com





jobs:
  custom-deploy:
    - name: Upload to Amazon S3
    runs-on: linux-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::360057177229:role/S3-FTP-Role
        aws-region: eu-west-2

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://aws-codedeploy-nodejs-eu-west-2

      - name: AWS login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to S3
        run: git push heroku master
