name: AWS Build n Deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: linux
     steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
         restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         - name: Use Node.js 16.x
            uses: actions/setup-node@v1
            with:
              node-version: 16.x
          - name: Install dependencies
            run: yarn  install
          - name: Build
            run: yarn build
